# Generated by Django 6.0.2 on 2026-03-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nif', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta_conducao', models.CharField(max_length=12)),
                ('ano_nascimento', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('nivel_conforto', models.CharField(choices=[('basico', 'Básico'), ('luxuoso', 'Luxuoso')], max_length=10)),
                ('estado', models.CharField(choices=[('Em espera', 'Em Espera'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Suspenso', 'Suspenso')], max_length=12)),
                ('n_passageiros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('quilometragem', models.IntegerField()),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('nivel_conforto', models.CharField(choices=[('basico', 'Básico'), ('luxuoso', 'Luxuoso')], max_length=10)),
                ('tipo_motor', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'taxi',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('genero', models.CharField(choices=[('femenino', 'Feminino'), ('masculino', 'Masculino'), ('outro', 'Outro'), ('sem resposta', 'Sem Resposta')], max_length=15)),
                ('senha', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('id_motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motorista')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
                ('id_taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taxi')),
            ],
        ),
        migrations.CreateModel(
            name='Reabastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euros', models.IntegerField()),
                ('kwh', models.IntegerField(blank=True, null=True)),
                ('litros', models.IntegerField(blank=True, null=True)),
                ('quilometragem_inicial', models.IntegerField()),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
        ),
        migrations.AddField(
            model_name='motorista',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizador'),
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.utilizador')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.utilizador'),
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quilometros', models.IntegerField()),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('nivel_conforto', models.CharField(choices=[('basico', 'Básico'), ('luxuoso', 'Luxuoso')], max_length=10)),
                ('preco', models.IntegerField()),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
        ),
    ]
