# Generated by Django 6.0.2 on 2026-04-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=15)),
                ('password', models.CharField(max_length=40)),
                ('is_banned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nif', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('license_plate', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('purchase_year', models.CharField(max_length=4)),
                ('mileage', models.IntegerField()),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('comfort_level', models.CharField(choices=[('basic', 'Basic'), ('luxury', 'Luxury')], max_length=10)),
                ('engine_type', models.CharField(max_length=40)),
                ('num_passengers', models.IntegerField()),
            ],
            options={
                'db_table': 'taxi',
            },
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'time_interval',
            },
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('comfort_level', models.CharField(choices=[('basic', 'Basic'), ('luxury', 'Luxury')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('suspended', 'Suspended')], max_length=12)),
                ('num_passengers', models.IntegerField()),
            ],
            options={
                'db_table': 'trip_request',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('license_number', models.CharField(max_length=12)),
                ('birth_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taxi')),
                ('real_interval', models.ForeignKey(blank=True, help_text='Real interval (actual start and end of the shift)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_real', to='api.timeinterval')),
                ('scheduled_interval', models.ForeignKey(help_text='Scheduled interval (planned start and end)', on_delete=django.db.models.deletion.CASCADE, related_name='shift_scheduled', to='api.timeinterval')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('kwh', models.IntegerField(blank=True, null=True)),
                ('liters', models.IntegerField(blank=True, null=True)),
                ('initial_mileage', models.IntegerField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shift')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timeinterval')),
            ],
            options={
                'db_table': 'refueling',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometers', models.IntegerField()),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('comfort_level', models.CharField(choices=[('basic', 'Basic'), ('luxury', 'Luxury')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_passengers', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRIVER_ACCEPTED', 'Driver Accepted'), ('CLIENT_ACCEPTED', 'Client Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('interval', models.ForeignKey(db_column='id_interval', on_delete=django.db.models.deletion.CASCADE, to='api.timeinterval')),
                ('shift', models.ForeignKey(db_column='id_shift', on_delete=django.db.models.deletion.CASCADE, to='api.shift')),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
