# Generated by Django 6.0.2 on 2026-03-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='gestor',
            table='gestor',
        ),
        migrations.AlterModelTable(
            name='motorista',
            table='motorista',
        ),
        migrations.AlterModelTable(
            name='periodo',
            table='periodo_tempo',
        ),
        migrations.AlterModelTable(
            name='utilizador',
            table='utilizador',
        ),
    ]
