# Generated by Django 6.0.2 on 2026-03-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cliente_table_alter_gestor_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avaliacao',
            table='avaliacao',
        ),
        migrations.AlterModelTable(
            name='fatura',
            table='fatura',
        ),
        migrations.AlterModelTable(
            name='pedidoviagem',
            table='pedido_viagem',
        ),
        migrations.AlterModelTable(
            name='reabastecimento',
            table='reabastecimento',
        ),
        migrations.AlterModelTable(
            name='turno',
            table='turno',
        ),
        migrations.AlterModelTable(
            name='viagem',
            table='viagem',
        ),
    ]
