# Generated by Django 6.0.2 on 2026-03-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_avaliacao_table_alter_fatura_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='id',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_user',
            field=models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.utilizador'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='id_user',
            field=models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.utilizador'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='id_user',
            field=models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.utilizador'),
        ),
    ]
