version: '3.8'

services:
  # Servidor Backend (Django/Gunicorn)
  backend:
    image: europe-southwest1-docker.pkg.dev/${PROJECT_ID}/tuxy-repo/backend:latest
    container_name: tuxy_backend
    restart: always
    env_file:
      - .env
    # Não expõe porta para o exterior, apenas internamente no docker network para o nginx
    expose:
      - "8000"

  # Nginx para Servir Frontend e atuar como Reverse Proxy Interno
  nginx:
    image: europe-southwest1-docker.pkg.dev/${PROJECT_ID}/tuxy-repo/frontend:latest
    container_name: tuxy_nginx
    restart: always
    depends_on:
      - backend
    # Ouve na porta 8000 conforme arquitetura do Redes.pdf
    ports:
      - "8000:80"
