name: Deploy TUXY to GCP
on:
  push:
    branches: [ main ]

env:
  GAR_LOCATION: europe-southwest1
  REPOSITORY: tuxy-repo
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Frontend
        run: |
          TAG="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/frontend:latest"
          docker build -t "$TAG" ./frontend
          docker push "$TAG"

      - name: Build and Push Backend
        run: |
          TAG="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/backend:latest"
          docker build -t "$TAG" ./backend
          docker push "$TAG"

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_APP_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tuxy
            docker compose pull
            docker compose up -d
